### PR TITLE
Back repo as GDExtension

### PR DESCRIPTION
**Pull request by GuilhermeGSousa**
- [ ] Implement AnimationNodeExtension in godot
- [x] Fix builds of MMAnimationNode
- [x] Fix CI

### CODE REVIEW

**Comment by fire** [comment]
https://github.com/godotengine/godot-cpp-template is useful!

**Comment by fire** [comment]
@GuilhermeGSousa I propose we go in this order:

## AnimationNodeExtension 

There is a race to get this into the Godot Engine 4.4 version.

## Bone features

While we wait, we can develop the bone feature.

## godot-motion-matching GDExtension

When AnimationNodeExtension is in the Godot Engine master branch, we can work on this.

**Comment by GuilhermeGSousa** [comment]
@fire I have some work done in godot, I needed these changes to be able to start testing things
https://github.com/godotengine/godot/pull/99181

**Comment by GeorgeS2019** [comment]
Which version of Godot 4 will work with this GDectension?

**Comment by GuilhermeGSousa** [comment]
Whichever version has this change
https://github.com/godotengine/godot/pull/99181
so probably 4.5? I dunno

**Comment by GeorgeS2019** [comment]
Not to be unfair to you, if you could provide windows exe of this version, we could continue to follow your demo. Just a feedback

**Pull request merged**
