### PR TITLE
Convert repo into engine module

### PR DESCRIPTION
**Pull request by GuilhermeGSousa**

### CODE REVIEW

**Comment by GuilhermeGSousa** [comment]
@fire opened this one from your branch, the only conflicts seem to come from having deleted the demo folder

**Comment by fire** [comment]
Look good

**Comment by GeorgeS2019** [comment]
@fire 
image


Is it normal to **recommend merging** before   making sure that  the CI from https://github.com/V-Sekai/godot-motion-matching/ is working?

**Comment by fire** [comment]
Yes, because it was a conversion of a gdextension to github modules and we tested it specific builds locally and it passed once on https://github.com/V-Sekai/godot/actions/runs/11536674185

image

**Comment by fire** [comment]
We were more concerned that baking did not work and thus I shared the work so that @GuilhermeGSousa can work on fixing feature baking.

**Pull request merged**
