### PR TITLE
Implement Motion Matching Animation Node

### PR DESCRIPTION
**Pull request by GuilhermeGSousa**
Pending submission of https://github.com/godotengine/godot/pull/99181#event-15331106370

### CODE REVIEW

**Comment by GeorgeS2019** [comment]
why none of the Github Action works?

**Comment by GuilhermeGSousa** [comment]
All of this code is based on a version of godot that has the changes from the PR I posted above. We have no way of having a Github Action that uses a version of godot that has those changes, so more likely is that builds will fail until the PR gets merged

**Comment by GeorgeS2019** [comment]
Ok, we need to wait for Juan to come back from holiday. Thx

**Comment by GuilhermeGSousa** [comment]
Hey @fire! I think the essentials that this repo was missing are all here now. Still a lot to do, but once this is submitted I'll make a new release that I'll push to the asset store.

**Comment by GeorgeS2019** [comment]
If you need to use a specific version of Godot that includes changes from a **pending** pull request (source ChatGPt):

**Build from Source**: One option is to build Godot from the source code in your GitHub Actions workflow. You can use the specific branch or commit that includes the changes you need. This will involve adding steps to your workflow to clone the Godot repository, check out the specific branch, and build it.

```yaml

name: Godot CI

on:
  push:
    branches:
      - your-branch-name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y scons pkg-config libx11-dev libxcursor-dev libxinerama-dev libgl1-mesa-dev libglu1-mesa-dev libasound2-dev libpulse-dev libudev-dev libxi-dev libxrandr-dev yasm python3

      - name: Clone Godot repository
        run: git clone --branch your-branch-name https://github.com/godotengine/godot.git

      - name: Build Godot
        run: |
          cd godot
          scons platform=linuxbsd

      - name: Use custom Godot build
        run: |
          export PATH="$PWD/bin:$PATH"
          godot --version
          godot --build --path path/to/your/project

```

**Comment by fire** [comment]
> Only a suggestion, implementing it could be taking a lot of time:
> 
> If you need to use a specific version of Godot that includes changes from a **pending** pull request 

We already implemented that in https://github.com/V-Sekai/world-godot/blob/main/Justfile. See also https://github.com/godotengine/build-containers

**Comment by GuilhermeGSousa** [comment]
I don't think we'll need to pull godot's builds for specific PRs for now, especially now that the one we care about has been merged. I'll just go ahead and merge this one.

**Pull request merged**
